### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Fluxencap** [Dealman/Frankensteiner#5]
i cant download this because windows smartscreen is blocking it how do i fix it?

**Comment by Dealman** [comment]
Sorry for the late response, it probably detects it as potentially dangerous because I haven't signed it? You'd have to temporarily disable Windows SmartScreen when you want to use it I guess.

If you right-click the executable after downloading it and going to properties, do you have an option to unblock it? If so, try that and see if it works afterwards.
